apiVersion: v1
kind: Template
metadata:
  name: kafka-instance-template
  annotations:
    description: "Template for the creation of a Kafka cluster"
parameters:
- description: The name of the staging project
  displayName: Number of kafka instance and zookeeper instances to create
  name: REPLICA_COUNT
  value: "3"
  required: true
- description: Minimum ISR
  displayName: Minimum ISR
  name: MIN_ISR
  value: "2"
  required: true
objects:
- apiVersion: kafka.strimzi.io/v1beta1
  kind: Kafka
  metadata:
    name: my-cluster
    namespace: user1-cloudnativeapps
  spec:
    kafka:
      version: 2.5.0
      replicas: ${{REPLICA_COUNT}}
      listeners:
        plain:
          authentiation:
            type: scram-sha-512
        tls:
          authentiation:
            type: tls
      config:
        offsets.topic.replication.factor: ${{REPLICA_COUNT}}
        transaction.state.log.replication.factor: ${{REPLICA_COUNT}}
        transaction.state.log.min.isr: ${{MIN_ISR}}
        log.message.format.version: '2.3'
      storage:
        type: ephemeral
    zookeeper:
      replicas: ${{REPLICA_COUNT}}
      storage:
        type: ephemeral
    entityOperator:
      topicOperator:
        reconciliationIntervalSeconds: 90
      userOperator:
        reconciliationIntervalSeconds: 120
