apiVersion: v1
kind: Template
metadata:
  name: kafka-instance-template
  annotations:
    description: "Template for the creation of a Kafka cluster"
parameters:
- description: The name of the staging project
  displayName: Number of kafka instance and zookeeper instances to create
  name: REPLICA_COUNT
  value: "3"
  required: true
- description: Minimum ISR
  displayName: Minimum ISR
  name: MIN_ISR
  value: "2"
  required: true
objects:
- apiVersion: kafka.strimzi.io/v1beta1
  kind: Kafka
  metadata:
    name: my-cluster
  spec:
    kafka:
      version: 2.6.0
      replicas: ${{REPLICA_COUNT}}
      listeners:
        - name: plain
          port: 9092
          type: internal
          tls: false
        - name: tls
          port: 9093
          type: internal
          tls: true
        # This is used for accessing the kafka cluster locally.  Port forwarding doesn't 
        # appear to work
        - name: external
          port: 9094
          type: route
          tls: true
      config:
        offsets.topic.replication.factor: ${{REPLICA_COUNT}}
        transaction.state.log.replication.factor: ${{REPLICA_COUNT}}
        transaction.state.log.min.isr: ${{MIN_ISR}}
        log.message.format.version: '2.6'
        num.partitions: 100
      storage:
        type: ephemeral
    zookeeper:
      replicas: ${{REPLICA_COUNT}}
      storage:
        type: ephemeral
    entityOperator:
      topicOperator: {}
      userOperator: {}
