apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client-local
spec:
  params:
    - name: COMMANDS
      type: string 
  steps:
    - name: run-commands
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/usr/bin/env bash
        $(inputs.params.COMMANDS)
