apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: ct-knative-run-
spec:
    taskRef:
      kind: ClusterTask
      name: kn
    params:
    - name: ARGS
      value:
      - service
      - update
      - payment
      - --image 
      - image-registry.openshift-image-registry.svc:5000/kn-demo-dev/payment:latest
      - --revision-name 
      - "{{.Service}}-{{.Generation}}"
      - -e 
      - "mp.messaging.outgoing.payments.bootstrap.servers=my-cluster-kafka-bootstrap.kn-demo-dev:9092"
      - -n
      - kn-demo-dev
      - --concurrency-limit=1
    serviceAccountName: pipeline