= Serverless Demo: Setup =
:experimental:
:imagesdir: images
:toc:
:toclevels: 4

== Installing Demo ==
[IMPORTANT]
====
To limit the amount of incompatibility in setting up the demo, all the commands that are listed are expected to be run in an appropriately setup container.  You will find this as part of the instructions below and it's important not to skip this step

This demo also supports the link:https://code.visualstudio.com/docs/remote/containers[VS Code Remote Development (Containers)] as can be seen in the .devcontainer directory.  If you use the terminal in VSCode and run this repo in a container, then you don't need to follow the commands to run docker in the shell as your terminal will already be running in a container that has all the necessary runtime components
====

. Fork or clone this repo onto your local machine
. `cd` to the root of the folder
. Run the following command:
** NOTE: If you are not using `zsh` locally, you can omit the `-v ~/.oh-my-zsh:/home/jboss/.oh-my-zsh` part of the `docker run` command below
+
----
docker run --rm -it -v ~/.kube:/home/jboss/.kube -v /var/run/docker.sock.raw:/var/run/docker.sock -v ~/.oh-my-zsh:/home/jboss/.oh-my-zsh -v $(pwd):/workspaces/serverless-demo -w /workspaces/serverless-demo quay.io/mhildenb/kn-demo-shell /bin/zsh
----
+
. Be sure to log into your OpenShift cluster with cluster-admin permissions
. Check to make sure your cluster's version is >= 4.6.8
+
----
oc get clusterversion --no-headers | awk '{print $2}'
----
+
.. [red]#If clusterversion is < 4.6.8 then run this command (see link:https://docs.openshift.com/container-platform/4.6/updating/updating-cluster-cli.html#update-upgrading-cli_updating-cluster-cli[here] for more details):#
+
----
oc admin upgrade --to-latest
----
+
. OPTIONALLY override `PROJECT_PREFIX` to the name prefix name you'd like the projects associated with this demo to have (default: `kn-demo`)
. Run the following command to setup the demo:
** `-i` flag sets up all pre-requisites
** `-p` is not necessary if you don't want to change the default `PROJECT_PREFIX`
** `-s` [optional] Skip installation of the Serverless Operator (to allow it being done manually for sake of demonstration)
+
----
$DEMO_HOME/scripts/create-demo.sh -i -p $PROJECT_PREFIX
----
+
. If the installation was successful, you should see the following:
+
----
Demo installation completed without error.
Finishing with return value of 0
----
+
. Once completed, you can now follow the instructions link:walkthrough/demo-walkthrough.adoc[in this walkthrough]

== Uninstalling the Demo ==

You can remove the aspects from this demo from your cluster by running the following command (from within the container that was setup above)

* The `-p` flag is not necessary if you haven't changed the `PROJECT_PREFIX` from the default
* [red]#The `-f` flag will remove all the operators (and associated CRDs) that were installed to support the demo.  This could be an issue if you have other things in the cluster using these resources (e.g. Serverless).  If you only want the projects associated with the demo to be removed and not all the prerequisite operators, omit the `-f` flag#

----
$DEMO_HOME/scripts/uninstall.sh -f -p $PROJECT_PREFIX
----

== Appendix ==

=== Creating new images of "coolstore" demo services

The source code for the services used in this demo can be found in the `coolstore` submodule.

For easily creating new `payment-service` images (using quarkus container and jib) for use in the demo (such as seen in link:https://quay.io/repository/mhildenb/homemade-serverless-java[this registry] and link:https://quay.io/repository/mhildenb/homemade-serverless-native[this registry]) see the link:../scripts/create-payment-service.sh[create-payment-service.sh] script.