kind: Deployment
apiVersion: apps/v1
metadata:
  name: crw-maven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crw-maven
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crw-maven
        deploymentconfig: crw-maven
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: crw-maven
          image: >-
            quay.io/mhildenb/crw-maven:1.3.4
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            runAsUser: 0
            # capabilities: 
            #   add: [ CAP_]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600