apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source-orders
  labels:
    app.kubernetes.io/part-of: focus
    app: kafka-source-orders
    app.kubernetes.io/component: kafka-source-orders
    app.kubernetes.io/instance: kafka-source-orders
spec:
  consumerGroup: payment-consumer-group
  bootstrapServers: 
  - my-cluster-kafka-bootstrap:9092
  topics: 
  - orders
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: payment