apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource 
metadata:
  name: event-greeter-cronjob-source
spec:
  # call every minute (the shortest time between calls for the cronjobsource)
  schedule: "* * * * *"
  data: '{"message": "Thanks for doing Knative Tutorial"}'
  sink: 
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: payment