kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
#    my-cluster-kafka has a tendency to disappear and reappear and when doing so can crash the 
#    topology view.  Best not to connect it here
#    app.openshift.io/connects-to: my-cluster-kafka
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"},"creationTimestamp":"2019-11-19T12:31:52Z","generation":2,"labels":{"app":"payment"},"name":"payment","namespace":"user1-cloudnativeapps","resourceVersion":"1277023","selfLink":"/apis/apps.openshift.io/v1/namespaces/user1-cloudnativeapps/deploymentconfigs/payment","uid":"9082f3c1-0ac8-11ea-a85f-0a580a82001e"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"app":"payment","deploymentconfig":"payment"},"strategy":{"activeDeadlineSeconds":21600,"resources":{},"rollingParams":{"intervalSeconds":1,"maxSurge":"25%","maxUnavailable":"25%","timeoutSeconds":600,"updatePeriodSeconds":1},"type":"Rolling"},"template":{"metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"},"creationTimestamp":null,"labels":{"app":"payment","deploymentconfig":"payment"}},"spec":{"containers":[{"image":"image-registry.openshift-image-registry.svc:5000/user1-cloudnativeapps/payment@sha256:dde136f4ce19af9a6b59ca0a53d0d208c53e9257c25afa66d0fbfb006c48269a","imagePullPolicy":"Always","name":"payment","ports":[{"containerPort":8080,"protocol":"TCP"},{"containerPort":8443,"protocol":"TCP"},{"containerPort":8778,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}},"test":false,"triggers":[{"type":"ConfigChange"},{"imageChangeParams":{"automatic":true,"containerNames":["payment"],"from":{"kind":"ImageStreamTag","name":"payment:latest","namespace":"user1-cloudnativeapps"},"lastTriggeredImage":"image-registry.openshift-image-registry.svc:5000/user1-cloudnativeapps/payment@sha256:dde136f4ce19af9a6b59ca0a53d0d208c53e9257c25afa66d0fbfb006c48269a"},"type":"ImageChange"}]},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2019-11-19T12:32:01Z","lastUpdateTime":"2019-11-19T12:32:22Z","message":"replication
      controller \"payment-1\" successfully rolled
      out","reason":"NewReplicationControllerAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2019-11-19T16:01:09Z","lastUpdateTime":"2019-11-19T16:01:09Z","message":"Deployment
      config has minimum
      availability.","status":"True","type":"Available"}],"details":{"causes":[{"type":"ConfigChange"}],"message":"config
      change"},"latestVersion":1,"observedGeneration":2,"readyReplicas":1,"replicas":1,"unavailableReplicas":0,"updatedReplicas":1}}
    openshift.io/generated-by: OpenShiftNewApp
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/user1-cloudnativeapps/deploymentconfigs/payment
  resourceVersion: '1875870'
  name: payment
  uid: 980d93da-0df6-11ea-8f1c-0a580a800056
  creationTimestamp: '2019-11-23T13:38:55Z'
  generation: 2
  namespace: user1-cloudnativeapps
  labels:
    app: payment
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - payment
        from:
          kind: ImageStreamTag
          namespace: user1-cloudnativeapps
          name: 'payment:latest'
        lastTriggeredImage: >-
          image-registry.openshift-image-registry.svc:5000/user1-cloudnativeapps/payment@sha256:efc674016f9e37f39f2bc214d5b35fa459244b57989136ee091e5cc793aa4780
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: payment
    deploymentconfig: payment
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payment
        deploymentconfig: payment
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: payment
          image: >-
            image-registry.openshift-image-registry.svc:5000/user1-cloudnativeapps/payment@sha256:efc674016f9e37f39f2bc214d5b35fa459244b57989136ee091e5cc793aa4780
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  observedGeneration: 2
  details:
    message: config change
    causes:
      - type: ConfigChange
  availableReplicas: 1
  unavailableReplicas: 0
  latestVersion: 1
  updatedReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2019-11-27T02:16:58Z'
      lastTransitionTime: '2019-11-27T02:16:58Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2019-11-27T02:16:59Z'
      lastTransitionTime: '2019-11-27T02:16:37Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "payment-1" successfully rolled out
  replicas: 1
  readyReplicas: 1
