kind: Service
apiVersion: v1
metadata:
  name: payment
  namespace: user1-cloudnativeapps
  selfLink: /api/v1/namespaces/user1-cloudnativeapps/services/payment
  uid: 8e8a7a4e-0df6-11ea-978f-0a8adb4f8fe6
  resourceVersion: '648371'
  creationTimestamp: '2019-11-23T13:38:39Z'
  labels:
    app: payment
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"},"creationTimestamp":"2019-11-19T12:31:52Z","labels":{"app":"payment"},"name":"payment","namespace":"user1-cloudnativeapps","resourceVersion":"1149117","selfLink":"/api/v1/namespaces/user1-cloudnativeapps/services/payment","uid":"90862a07-0ac8-11ea-8e02-021093040592"},"spec":{"clusterIP":"172.30.203.152","ports":[{"name":"8080-tcp","port":8080,"protocol":"TCP","targetPort":8080},{"name":"8443-tcp","port":8443,"protocol":"TCP","targetPort":8443},{"name":"8778-tcp","port":8778,"protocol":"TCP","targetPort":8778}],"selector":{"app":"payment","deploymentconfig":"payment"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
    openshift.io/generated-by: OpenShiftNewApp
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
  selector:
    app: payment
    deploymentconfig: payment
  clusterIP: 172.30.203.152
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
