apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2019-11-19T12:31:52Z"
    labels:
      app: payment
    name: payment
  spec:
    clusterIP: 172.30.203.152
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: payment
      deploymentconfig: payment
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2019-11-19T12:31:52Z"
    generation: 2
    labels:
      app: payment
      app.kubernetes.io/part-of: focus
    name: payment
    namespace: user1-cloudnativeapps
    resourceVersion: "1277023"
    selfLink: /apis/apps.openshift.io/v1/namespaces/user1-cloudnativeapps/deploymentconfigs/payment
    uid: 9082f3c1-0ac8-11ea-a85f-0a580a82001e
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: payment
      deploymentconfig: payment
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: payment
          deploymentconfig: payment
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/user1-cloudnativeapps/payment@sha256:dde136f4ce19af9a6b59ca0a53d0d208c53e9257c25afa66d0fbfb006c48269a
          imagePullPolicy: Always
          name: payment
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - payment
        from:
          kind: ImageStreamTag
          name: payment:latest
          namespace: user1-cloudnativeapps
        lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/user1-cloudnativeapps/payment@sha256:dde136f4ce19af9a6b59ca0a53d0d208c53e9257c25afa66d0fbfb006c48269a
      type: ImageChange
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: "2019-11-19T12:26:35Z"
    labels:
      app: payment
    name: payment
    namespace: user1-cloudnativeapps
    resourceVersion: "1146197"
    selfLink: /apis/build.openshift.io/v1/namespaces/user1-cloudnativeapps/buildconfigs/payment
    uid: d3edea58-0ac7-11ea-a85f-0a580a82001e
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: payment:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: openjdk18-openshift:1.5
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: LS7YPn15Rv25H9WQccMk
      type: GitHub
    - generic:
        secret: xdeijCP8ZYV6-Dz5Yjl5
      type: Generic
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: "2019-11-19T12:26:35Z"
    generation: 1
    labels:
      app: payment
    name: payment
  spec:
    lookupPolicy:
      local: false